server:
  port: 8084

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
        - id: MS-GREETING
          uri: lb://MS-GREETING
          predicates:
            - Path=/ws/v1/item/**
            
        - id: MS-CARD
          uri: lb://MS-CARD
          predicates:
            - Path=/ws/v1/card/** 

        - id: SX
          uri: lb://SX
          predicates:
            - Path=/ws/v1/oauth/** ,/ws/v1/**
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka