server:
  port: 8001

spring:
  application:
    name: api-gateway
    
  cloud:
    gateway:
      routes:
        - id: MS-LIBRARY
          uri: lb://MS-LIBRARY
          predicates:
            - Path=/ws/liberary/**
          filters:
          - PreGatewayFilter
                      
        - id: MS-CARD
          uri: lb://MS-CARD
          predicates:
            - Path=/ws/card/** 
          filters:
          - PreGatewayFilter            

        - id: USER-SETTING
          uri: lb://USER-SETTING
          predicates:
            - Path=/ws/oauth/** ,/ws/v1/**
#          filters:
#          - PreGatewayFilter
  
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka